import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";

import SvgSpritesComponent from "./components/ui/common/svgSprites/SvgSpritesComponent";
import AuthProvider from "./components/providers/authProvider/AuthProvider";

import "./globals.scss";

const OpenSansFont = Open_Sans({
  variable: "--open-sans-font",
  weight: "variable",
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "Qwins",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${OpenSansFont.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
        <Toaster position="top-center" richColors visibleToasts={5} />
        <SvgSpritesComponent />
      </body>
    </html>
  );
}
