import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.scss";

const OpenSansFont = Open_Sans({
  variable: "--open-sans-font",
  weight: "variable",
  display: "swap",
});

export const metadata: Metadata = {
  title: "1Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${OpenSansFont.variable}`}>{children}</body>
    </html>
  );
}
